### ISSUE TITLE
Unable to retrive contents of torrent containing many files

### ISSUE THREAD

**Issue by prateekkathal** [adriengibrat/torrent-rw#28]
Hello, 

First of all, Thank You for this amazing Library/Package!

I am facing some issue getting the list of torrents containing almost **40-50 files**. Let's say I have a torrent file containing more than 50 files in this manner
- Directory - 1
 - -- File 1
- Directory - 2
 - -- File 2

The `content()` function return an empty Array in this case.

Can you please look into it once?

Thanks,

**Comment by adriengibrat** [comment]
seems related to #22

**Comment by adriengibrat** [comment]
should be fixed by 	404232d, keep me posted if it works well, i'm not using or actively maintaining this lib...

**Comment by prateekkathal** [comment]
Thanks for working on it... But the problem still seems to exist

After doing `get_content()` I still get an empty array.

I did `print_r()` and the I got this **Array()**

**Comment by adriengibrat** [comment]
please provide the torrent file, and the code you used to read its content

**Comment by adriengibrat** [comment]
please be sure the torrent file was correctly generated, the bug fixed was about creating torrent, i'm pretty sure there is no issue when reading torrent content...

**Comment by prateekkathal** [comment]
Hello, 

Sry for the late reply. When I first reported this issue, I was talking about the reading part only. I am currently using your library to read torrents file only. 

I have attached 2 torrent files. Please have a look at them and let me know. 

I am running your code in CodeIgniter and everything seems to work perfectly fine, except for the part where I have **folders inside folders**

Following is the function I am using to get the contents from a torrent file. 

    function get_torrent_content($torrent_path) {
	    $torrent = new Torrent($torrent_path);
	    return $torrent->content();
    }

[Torrents.zip](https://github.com/adriengibrat/torrent-rw/files/291305/Torrents.zip)

Let me know. Thanks for the great support :)

**Comment by adriengibrat** [comment]
I can't reproduce any pb with the provided torrent files:
my test file:
```php
<?php
require_once 'Torrent.php';
$torrent = new Torrent('../[AnimeRG] Death Note (Complete) [Blu-Ray] [Multi] [1080p] [khatake2].torrent');
print_r($torrent->content());
```
Are you sure `$torrent_path` is a valid path (tha can be resolved by your script) ?

**Comment by prateekkathal** [comment]
Yes! It is a valid path, everything seems to be running fine for the rest of the torrent files. 

Can you try the other torrent file once? Is that working fine for you?

**Comment by adriengibrat** [comment]
Of course I've tested both torrent you provided. With out any issue.

**Comment by adriengibrat** [comment]
Check `$torrent->errors ()` in your `get_torrent_content` method.

**Comment by adriengibrat** [comment]
i'm closing the issue, re open if you have new input / test file to provide
